using System;
using System.Collections.Generic;
using System.Text;

using System.Data;
using DataEntity;

namespace DataAccess.Operate
{
    public class DA_OfficeAutomation_Document_Feasibility_Inherit : DA_OfficeAutomation_Document_Feasibility_Operate
    {
        /// <summary>
        /// 通过MainID查询
        /// </summary>
        /// <param name="mainID"></param>
        /// <returns></returns>
        public DataSet SelectByMainID(string mainID)
        {
            string sql = "SELECT  [OfficeAutomation_Document_Feasibility_ID]"
                           + "           ,[OfficeAutomation_Document_Feasibility_MainID]"
                           + "           ,[OfficeAutomation_Document_Feasibility_Apply]"
                           + "           ,[OfficeAutomation_Document_Feasibility_ApplyDate]"
                           + "           ,[OfficeAutomation_Document_Feasibility_ApplyID]"
                           + "           ,[OfficeAutomation_Document_Feasibility_Department]"
                           + "           ,[OfficeAutomation_Document_Feasibility_OpenType]"
                           + "           ,[OfficeAutomation_Document_Feasibility_Branch]"
                           + "           ,[OfficeAutomation_Document_Feasibility_TurnBranch]"
                           + "           ,[OfficeAutomation_Document_Feasibility_AreaManager]"
                           + "           ,[OfficeAutomation_Document_Feasibility_WorkingDepartmentNum]"
                           + "           ,[OfficeAutomation_Document_Feasibility_PrebuildDepartmentNum]"
                           + "           ,[OfficeAutomation_Document_Feasibility_lDepartmentType]"
                           + "           ,[OfficeAutomation_Document_Feasibility_lMajordomo]"
                           + "           ,[OfficeAutomation_Document_Feasibility_Contacter]"
                           + "           ,[OfficeAutomation_Document_Feasibility_ContactPhone]"
                           + "           ,[OfficeAutomation_Document_Feasibility_LastYearSituation1]"
                           + "           ,[OfficeAutomation_Document_Feasibility_LastYearSituation2]"
                           + "           ,[OfficeAutomation_Document_Feasibility_LastYearSituation3]"
                           + "           ,[OfficeAutomation_Document_Feasibility_LastYearSituation4]"
                           + "           ,[OfficeAutomation_Document_Feasibility_LastYearSituation5]"
                           + "           ,[OfficeAutomation_Document_Feasibility_LastYearSituation6]"
                           + "           ,[OfficeAutomation_Document_Feasibility_LastYearSituation7]"
                           + "           ,[OfficeAutomation_Document_Feasibility_LastYearSituation8]"
                           + "           ,[OfficeAutomation_Document_Feasibility_LastYearSituation9]"
                           + "           ,[OfficeAutomation_Document_Feasibility_ThisYearMonth]"
                           + "           ,[OfficeAutomation_Document_Feasibility_ThisYearSituation1]"
                           + "           ,[OfficeAutomation_Document_Feasibility_ThisYearSituation2]"
                           + "           ,[OfficeAutomation_Document_Feasibility_ThisYearSituation3]"
                           + "           ,[OfficeAutomation_Document_Feasibility_ThisYearSituation4]"
                           + "           ,[OfficeAutomation_Document_Feasibility_ThisYearSituation5]"
                           + "           ,[OfficeAutomation_Document_Feasibility_ThisYearSituation6]"
                           + "           ,[OfficeAutomation_Document_Feasibility_ThisYearSituation7]"
                           + "           ,[OfficeAutomation_Document_Feasibility_ThisYearSituation8]"
                           + "           ,[OfficeAutomation_Document_Feasibility_ThisYearSituation9]"
                           + "           ,[OfficeAutomation_Document_Feasibility_BusinessSituation1]"
                           + "           ,[OfficeAutomation_Document_Feasibility_BusinessSituation2]"
                           + "           ,[OfficeAutomation_Document_Feasibility_BusinessSituation3]"
                           + "           ,[OfficeAutomation_Document_Feasibility_BusinessSituation4]"
                           + "           ,[OfficeAutomation_Document_Feasibility_BusinessSituation5]"
                           + "           ,[OfficeAutomation_Document_Feasibility_BusinessSituation6]"
                           + "           ,[OfficeAutomation_Document_Feasibility_BusinessSituation7]"
                           + "           ,[OfficeAutomation_Document_Feasibility_BusinessSituation8]"
                           + "           ,[OfficeAutomation_Document_Feasibility_BusinessSituation9]"
                           + "           ,[OfficeAutomation_Document_Feasibility_BusinessSituation10]"
                           + "           ,[OfficeAutomation_Document_Feasibility_BusinessSituation11]"
                           + "           ,[OfficeAutomation_Document_Feasibility_BusinessSituation12]"
                           + "           ,[OfficeAutomation_Document_Feasibility_BusinessSituation13]"
                           + "           ,[OfficeAutomation_Document_Feasibility_BusinessSituation14]"
                           + "           ,[OfficeAutomation_Document_Feasibility_BusinessSituation15]"
                           + "           ,[OfficeAutomation_Document_Feasibility_BusinessSituation16]"
                           + "           ,[OfficeAutomation_Document_Feasibility_BusinessSituation17]"
                           + "           ,[OfficeAutomation_Document_Feasibility_BusinessSituation18]"
                           + "           ,[OfficeAutomation_Document_Feasibility_ProfitSituation1]"
                           + "           ,[OfficeAutomation_Document_Feasibility_ProfitSituation2]"
                           + "           ,[OfficeAutomation_Document_Feasibility_ProfitSituation3]"
                           + "           ,[OfficeAutomation_Document_Feasibility_ProfitSituation4]"
                           + "           ,[OfficeAutomation_Document_Feasibility_ProfitSituation5]"
                           + "           ,[OfficeAutomation_Document_Feasibility_ProfitSituation6]"
                           + "           ,[OfficeAutomation_Document_Feasibility_ProfitSituation7]"
                           + "           ,[OfficeAutomation_Document_Feasibility_ProfitSituation8]"
                           + "           ,[OfficeAutomation_Document_Feasibility_ProfitSituation9]"
                           + "           ,[OfficeAutomation_Document_Feasibility_ProfitSituation10]"
                           + "           ,[OfficeAutomation_Document_Feasibility_ProfitSituation11]"
                           + "           ,[OfficeAutomation_Document_Feasibility_ProfitSituation12]"
                           + "           ,[OfficeAutomation_Document_Feasibility_ProfitSituation13]"
                           + "           ,[OfficeAutomation_Document_Feasibility_ProfitSituation14]"
                           + "           ,[OfficeAutomation_Document_Feasibility_ProfitSituation15]"
                           + "           ,[OfficeAutomation_Document_Feasibility_ProfitSituation16]"
                           + "           ,[OfficeAutomation_Document_Feasibility_ProfitSituation17]"
                           + "           ,[OfficeAutomation_Document_Feasibility_ProfitSituation18]"
                           + "           ,[OfficeAutomation_Document_Feasibility_AccumulationSituation1]"
                           + "           ,[OfficeAutomation_Document_Feasibility_AccumulationSituation2]"
                           + "           ,[OfficeAutomation_Document_Feasibility_AccumulationSituation3]"
                           + "           ,[OfficeAutomation_Document_Feasibility_AccumulationSituation4]"
                           + "           ,[OfficeAutomation_Document_Feasibility_AccumulationSituation5]"
                           + "           ,[OfficeAutomation_Document_Feasibility_AccumulationSituation6]"
                           + "           ,[OfficeAutomation_Document_Feasibility_AccumulationSituation7]"
                           + "           ,[OfficeAutomation_Document_Feasibility_AccumulationSituation8]"
                           + "           ,[OfficeAutomation_Document_Feasibility_AccumulationSituation9]"
                           + "           ,[OfficeAutomation_Document_Feasibility_AccumulationSituation10]"
                           + "           ,[OfficeAutomation_Document_Feasibility_AccumulationSituation11]"
                           + "           ,[OfficeAutomation_Document_Feasibility_AccumulationSituation12]"
                           + "           ,[OfficeAutomation_Document_Feasibility_AccumulationSituation13]"
                           + "           ,[OfficeAutomation_Document_Feasibility_AccumulationSituation14]"
                           + "           ,[OfficeAutomation_Document_Feasibility_AccumulationSituation15]"
                           + "           ,[OfficeAutomation_Document_Feasibility_RecentlyYear]"
                           + "           ,[OfficeAutomation_Document_Feasibility_RecentlySeason]"
                           + "           ,[OfficeAutomation_Document_Feasibility_StandardSituation1]"
                           + "           ,[OfficeAutomation_Document_Feasibility_StandardSituation2]"
                           + "           ,[OfficeAutomation_Document_Feasibility_StandardSituation3]"
                           + "           ,[OfficeAutomation_Document_Feasibility_StandardSituation4]"
                           + "           ,[OfficeAutomation_Document_Feasibility_StandardSituation5]"
                           + "           ,[OfficeAutomation_Document_Feasibility_StandardSituation6]"
                           + "           ,[OfficeAutomation_Document_Feasibility_StandardSituation7]"
                           + "           ,[OfficeAutomation_Document_Feasibility_StandardSituation8]"
                           + "           ,[OfficeAutomation_Document_Feasibility_StandardSituation9]"
                           + "           ,[OfficeAutomation_Document_Feasibility_StandardSituation10]"
                           + "           ,[OfficeAutomation_Document_Feasibility_StandardSituation11]"
                           + "           ,[OfficeAutomation_Document_Feasibility_StandardSituation12]"
                           + "           ,[OfficeAutomation_Document_Feasibility_StandardSituation13]"
                           + "           ,[OfficeAutomation_Document_Feasibility_StandardSituation14]"
                           + "           ,[OfficeAutomation_Document_Feasibility_StandardSituation15]"
                           + "           ,[OfficeAutomation_Document_Feasibility_RateBeginDate]"
                           + "           ,[OfficeAutomation_Document_Feasibility_RateEndDate]"
                           + "           ,[OfficeAutomation_Document_Feasibility_Address]"
                           + "           ,[OfficeAutomation_Document_Feasibility_Square]"
                           + "           ,[OfficeAutomation_Document_Feasibility_RentSituation]"
                           + "           ,[OfficeAutomation_Document_Feasibility_Deposit]"
                           + "           ,[OfficeAutomation_Document_Feasibility_SendCoast]"
                           + "           ,[OfficeAutomation_Document_Feasibility_PropertySituation]"
                           + "           ,[OfficeAutomation_Document_Feasibility_RentAndTurn]"
                           + "           ,[OfficeAutomation_Document_Feasibility_PowerAddS]"
                           + "           ,[OfficeAutomation_Document_Feasibility_MTelephone]"
                           + "           ,[OfficeAutomation_Document_Feasibility_MOptical]"
                           + "           ,[OfficeAutomation_Document_Feasibility_MonthlyPerformance]"
                           + "           ,[OfficeAutomation_Document_Feasibility_ReachDate]"
                           + "           ,[OfficeAutomation_Document_Feasibility_TotalCost]"
                           + "           ,[OfficeAutomation_Document_Feasibility_NormalCost]"
                           + "           ,[OfficeAutomation_Document_Feasibility_MonthProfit]"
                           + "           ,[OfficeAutomation_Document_Feasibility_MonthProfitRDate]"
                           + "           ,[OfficeAutomation_Document_Feasibility_ReturnPeriod]"
                           + "           ,[OfficeAutomation_Document_Feasibility_BankOnForecast]"
                           + "           ,[OfficeAutomation_Document_Feasibility_BuildArea]"
                           + "           ,[OfficeAutomation_Document_Feasibility_UsableArea]"
                           + "           ,[OfficeAutomation_Document_Feasibility_LeaseStartDate]"
                           + "           ,[OfficeAutomation_Document_Feasibility_LeaseEndDate]"
                           + "           ,[OfficeAutomation_Document_Feasibility_LeaseYears]"
                           + "           ,[OfficeAutomation_Document_Feasibility_LeaseMonths]"
                           + "           ,[OfficeAutomation_Document_Feasibility_IsRentFree]"
                           + "           ,[OfficeAutomation_Document_Feasibility_RentFreeStart]"
                           + "           ,[OfficeAutomation_Document_Feasibility_txtRentFreeEnd]"
                           + "           ,[OfficeAutomation_Document_Feasibility_RentFreeCount]"
                           + "           ,[OfficeAutomation_Document_Feasibility_MonthlyRentNoTax]"
                           + "           ,[OfficeAutomation_Document_Feasibility_MonthlyRentIncludeTax]"
                           + "           ,[OfficeAutomation_Document_Feasibility_MothlyTax]"
                           + "           ,[OfficeAutomation_Document_Feasibility_HasTax]"
                           + "           ,[OfficeAutomation_Document_Feasibility_MonthlyTaxRate]"
                           + "           ,[OfficeAutomation_Document_Feasibility_ManageCoast]"
                           + "           ,[OfficeAutomation_Document_Feasibility_ManageCoast2]"
                           + "           ,[OfficeAutomation_Document_Feasibility_WCoast]"
                           + "           ,[OfficeAutomation_Document_Feasibility_ECoast]"
                           + "           ,[OfficeAutomation_Document_Feasibility_Invoice]"
                           + "           ,[OfficeAutomation_Document_Feasibility_RentDeposit]"
                           + "           ,[OfficeAutomation_Document_Feasibility_WEDeposit]"
                           + "           ,[OfficeAutomation_Document_Feasibility_ManageDeposit]"
                           + "           ,[OfficeAutomation_Document_Feasibility_PackageInvoice]"
                           + "           ,[OfficeAutomation_Document_Feasibility_NPackageInvoice]"
                           + "           ,[OfficeAutomation_Document_Feasibility_PayReason]"
                           + "           ,[OfficeAutomation_Document_Feasibility_PayWay]"
                           + "           ,[OfficeAutomation_Document_Feasibility_PayObiect]"
                           + "           ,[OfficeAutomation_Document_Feasibility_POPhone]"
                           + "           ,[OfficeAutomation_Document_Feasibility_Collection]"
                           + "           ,[OfficeAutomation_Document_Feasibility_CollectionPhone]"
                           + "           ,[OfficeAutomation_Document_Feasibility_Relationship]"
                           + "           ,[OfficeAutomation_Document_Feasibility_StampDuty]"
                           + "           ,[OfficeAutomation_Document_Feasibility_StampDuty0]"
                           + "           ,[OfficeAutomation_Document_Feasibility_CompleteDate]"
                           + "           ,[OfficeAutomation_Document_Feasibility_FirstRent]"
                           + "           ,[OfficeAutomation_Document_Feasibility_LeaseDeposit]"
                           + "           ,[OfficeAutomation_Document_Feasibility_FSendCoast]"
                           + "           ,[OfficeAutomation_Document_Feasibility_FWEDeposit]"
                           + "           ,[OfficeAutomation_Document_Feasibility_FManageDeposit]"
                           + "           ,[OfficeAutomation_Document_Feasibility_FFMCoaet]"
                           + "           ,[OfficeAutomation_Document_Feasibility_FirstRentC]"
                           + "           ,[OfficeAutomation_Document_Feasibility_LeaseDepositC]"
                           + "           ,[OfficeAutomation_Document_Feasibility_FSendCoastC]"
                           + "           ,[OfficeAutomation_Document_Feasibility_FWEDepositC]"
                           + "           ,[OfficeAutomation_Document_Feasibility_FManageDepositC]"
                           + "           ,[OfficeAutomation_Document_Feasibility_FFMCoaetC]"
                           + "           ,[OfficeAutomation_Document_Feasibility_FirstRentT]"
                           + "           ,[OfficeAutomation_Document_Feasibility_LeaseDepositT]"
                           + "           ,[OfficeAutomation_Document_Feasibility_FSendCoastT]"
                           + "           ,[OfficeAutomation_Document_Feasibility_FWEDepositT]"
                           + "           ,[OfficeAutomation_Document_Feasibility_FManageDepositT]"
                           + "           ,[OfficeAutomation_Document_Feasibility_FFMCoaetT]"
                           + "           ,[OfficeAutomation_Document_Feasibility_RentName]"
                           + "           ,[OfficeAutomation_Document_Feasibility_RentReal]"
                           + "           ,[OfficeAutomation_Document_Feasibility_RentIdentity]"
                           + "           ,[OfficeAutomation_Document_Feasibility_RentMessage]"
                           + "           ,[OfficeAutomation_Document_Feasibility_EstateProperties]"
                           + "           ,[OfficeAutomation_Document_Feasibility_NatureTitle]"
                           + "           ,[OfficeAutomation_Document_Feasibility_NatureTitleO]"
                           + "           ,[OfficeAutomation_Document_Feasibility_Summary]"
                           + "           ,toam.OfficeAutomation_SerialNumber"
                           + "           ,tdoad.OfficeAutomation_Document_Name"
                           + "           ,toam.OfficeAutomation_Main_FlowStateID"
                           + " FROM [DB_EcOfficeAutomation].[dbo].[t_OfficeAutomation_Document_Feasibility] todi"
                           + " LEFT JOIN t_OfficeAutomation_Main toam ON toam.OfficeAutomation_Main_ID= todi.OfficeAutomation_Document_Feasibility_MainID"
                           + " LEFT JOIN t_Dic_OfficeAutomation_Document tdoad ON tdoad.OfficeAutomation_Document_ID = toam.OfficeAutomation_DocumentID"
                           + " WHERE OfficeAutomation_Document_Feasibility_MainID='" + mainID + "'";

            return RunSQL(sql);
        }

        /// <summary>
        /// 通过ID查询
        /// </summary>
        /// <param name="mainID"></param>
        /// <returns></returns>
        public DataSet SelectByID(string ID)
        {
            string sql = "SELECT  [OfficeAutomation_Document_Feasibility_ID]"
                           + "           ,[OfficeAutomation_Document_Feasibility_MainID]"
                           + "           ,[OfficeAutomation_Document_Feasibility_Apply]"
                           + "           ,[OfficeAutomation_Document_Feasibility_ApplyDate]"
                           + "           ,[OfficeAutomation_Document_Feasibility_ApplyID]"
                           + "           ,[OfficeAutomation_Document_Feasibility_Department]"
                           + "           ,[OfficeAutomation_Document_Feasibility_OpenType]"
                           + "           ,[OfficeAutomation_Document_Feasibility_Branch]"
                           + "           ,[OfficeAutomation_Document_Feasibility_TurnBranch]"
                           + "           ,[OfficeAutomation_Document_Feasibility_AreaManager]"
                           + "           ,[OfficeAutomation_Document_Feasibility_WorkingDepartmentNum]"
                           + "           ,[OfficeAutomation_Document_Feasibility_PrebuildDepartmentNum]"
                           + "           ,[OfficeAutomation_Document_Feasibility_lDepartmentType]"
                           + "           ,[OfficeAutomation_Document_Feasibility_lMajordomo]"
                           + "           ,[OfficeAutomation_Document_Feasibility_Contacter]"
                           + "           ,[OfficeAutomation_Document_Feasibility_ContactPhone]"
                           + "           ,[OfficeAutomation_Document_Feasibility_LastYearSituation1]"
                           + "           ,[OfficeAutomation_Document_Feasibility_LastYearSituation2]"
                           + "           ,[OfficeAutomation_Document_Feasibility_LastYearSituation3]"
                           + "           ,[OfficeAutomation_Document_Feasibility_LastYearSituation4]"
                           + "           ,[OfficeAutomation_Document_Feasibility_LastYearSituation5]"
                           + "           ,[OfficeAutomation_Document_Feasibility_LastYearSituation6]"
                           + "           ,[OfficeAutomation_Document_Feasibility_LastYearSituation7]"
                           + "           ,[OfficeAutomation_Document_Feasibility_LastYearSituation8]"
                           + "           ,[OfficeAutomation_Document_Feasibility_LastYearSituation9]"
                           + "           ,[OfficeAutomation_Document_Feasibility_ThisYearMonth]"
                           + "           ,[OfficeAutomation_Document_Feasibility_ThisYearSituation1]"
                           + "           ,[OfficeAutomation_Document_Feasibility_ThisYearSituation2]"
                           + "           ,[OfficeAutomation_Document_Feasibility_ThisYearSituation3]"
                           + "           ,[OfficeAutomation_Document_Feasibility_ThisYearSituation4]"
                           + "           ,[OfficeAutomation_Document_Feasibility_ThisYearSituation5]"
                           + "           ,[OfficeAutomation_Document_Feasibility_ThisYearSituation6]"
                           + "           ,[OfficeAutomation_Document_Feasibility_ThisYearSituation7]"
                           + "           ,[OfficeAutomation_Document_Feasibility_ThisYearSituation8]"
                           + "           ,[OfficeAutomation_Document_Feasibility_ThisYearSituation9]"
                           + "           ,[OfficeAutomation_Document_Feasibility_BusinessSituation1]"
                           + "           ,[OfficeAutomation_Document_Feasibility_BusinessSituation2]"
                           + "           ,[OfficeAutomation_Document_Feasibility_BusinessSituation3]"
                           + "           ,[OfficeAutomation_Document_Feasibility_BusinessSituation4]"
                           + "           ,[OfficeAutomation_Document_Feasibility_BusinessSituation5]"
                           + "           ,[OfficeAutomation_Document_Feasibility_BusinessSituation6]"
                           + "           ,[OfficeAutomation_Document_Feasibility_BusinessSituation7]"
                           + "           ,[OfficeAutomation_Document_Feasibility_BusinessSituation8]"
                           + "           ,[OfficeAutomation_Document_Feasibility_BusinessSituation9]"
                           + "           ,[OfficeAutomation_Document_Feasibility_BusinessSituation10]"
                           + "           ,[OfficeAutomation_Document_Feasibility_BusinessSituation11]"
                           + "           ,[OfficeAutomation_Document_Feasibility_BusinessSituation12]"
                           + "           ,[OfficeAutomation_Document_Feasibility_BusinessSituation13]"
                           + "           ,[OfficeAutomation_Document_Feasibility_BusinessSituation14]"
                           + "           ,[OfficeAutomation_Document_Feasibility_BusinessSituation15]"
                           + "           ,[OfficeAutomation_Document_Feasibility_BusinessSituation16]"
                           + "           ,[OfficeAutomation_Document_Feasibility_BusinessSituation17]"
                           + "           ,[OfficeAutomation_Document_Feasibility_BusinessSituation18]"
                           + "           ,[OfficeAutomation_Document_Feasibility_ProfitSituation1]"
                           + "           ,[OfficeAutomation_Document_Feasibility_ProfitSituation2]"
                           + "           ,[OfficeAutomation_Document_Feasibility_ProfitSituation3]"
                           + "           ,[OfficeAutomation_Document_Feasibility_ProfitSituation4]"
                           + "           ,[OfficeAutomation_Document_Feasibility_ProfitSituation5]"
                           + "           ,[OfficeAutomation_Document_Feasibility_ProfitSituation6]"
                           + "           ,[OfficeAutomation_Document_Feasibility_ProfitSituation7]"
                           + "           ,[OfficeAutomation_Document_Feasibility_ProfitSituation8]"
                           + "           ,[OfficeAutomation_Document_Feasibility_ProfitSituation9]"
                           + "           ,[OfficeAutomation_Document_Feasibility_ProfitSituation10]"
                           + "           ,[OfficeAutomation_Document_Feasibility_ProfitSituation11]"
                           + "           ,[OfficeAutomation_Document_Feasibility_ProfitSituation12]"
                           + "           ,[OfficeAutomation_Document_Feasibility_ProfitSituation13]"
                           + "           ,[OfficeAutomation_Document_Feasibility_ProfitSituation14]"
                           + "           ,[OfficeAutomation_Document_Feasibility_ProfitSituation15]"
                           + "           ,[OfficeAutomation_Document_Feasibility_ProfitSituation16]"
                           + "           ,[OfficeAutomation_Document_Feasibility_ProfitSituation17]"
                           + "           ,[OfficeAutomation_Document_Feasibility_ProfitSituation18]"
                           + "           ,[OfficeAutomation_Document_Feasibility_AccumulationSituation1]"
                           + "           ,[OfficeAutomation_Document_Feasibility_AccumulationSituation2]"
                           + "           ,[OfficeAutomation_Document_Feasibility_AccumulationSituation3]"
                           + "           ,[OfficeAutomation_Document_Feasibility_AccumulationSituation4]"
                           + "           ,[OfficeAutomation_Document_Feasibility_AccumulationSituation5]"
                           + "           ,[OfficeAutomation_Document_Feasibility_AccumulationSituation6]"
                           + "           ,[OfficeAutomation_Document_Feasibility_AccumulationSituation7]"
                           + "           ,[OfficeAutomation_Document_Feasibility_AccumulationSituation8]"
                           + "           ,[OfficeAutomation_Document_Feasibility_AccumulationSituation9]"
                           + "           ,[OfficeAutomation_Document_Feasibility_AccumulationSituation10]"
                           + "           ,[OfficeAutomation_Document_Feasibility_AccumulationSituation11]"
                           + "           ,[OfficeAutomation_Document_Feasibility_AccumulationSituation12]"
                           + "           ,[OfficeAutomation_Document_Feasibility_AccumulationSituation13]"
                           + "           ,[OfficeAutomation_Document_Feasibility_AccumulationSituation14]"
                           + "           ,[OfficeAutomation_Document_Feasibility_AccumulationSituation15]"
                           + "           ,[OfficeAutomation_Document_Feasibility_RecentlyYear]"
                           + "           ,[OfficeAutomation_Document_Feasibility_RecentlySeason]"
                           + "           ,[OfficeAutomation_Document_Feasibility_StandardSituation1]"
                           + "           ,[OfficeAutomation_Document_Feasibility_StandardSituation2]"
                           + "           ,[OfficeAutomation_Document_Feasibility_StandardSituation3]"
                           + "           ,[OfficeAutomation_Document_Feasibility_StandardSituation4]"
                           + "           ,[OfficeAutomation_Document_Feasibility_StandardSituation5]"
                           + "           ,[OfficeAutomation_Document_Feasibility_StandardSituation6]"
                           + "           ,[OfficeAutomation_Document_Feasibility_StandardSituation7]"
                           + "           ,[OfficeAutomation_Document_Feasibility_StandardSituation8]"
                           + "           ,[OfficeAutomation_Document_Feasibility_StandardSituation9]"
                           + "           ,[OfficeAutomation_Document_Feasibility_StandardSituation10]"
                           + "           ,[OfficeAutomation_Document_Feasibility_StandardSituation11]"
                           + "           ,[OfficeAutomation_Document_Feasibility_StandardSituation12]"
                           + "           ,[OfficeAutomation_Document_Feasibility_StandardSituation13]"
                           + "           ,[OfficeAutomation_Document_Feasibility_StandardSituation14]"
                           + "           ,[OfficeAutomation_Document_Feasibility_StandardSituation15]"
                           + "           ,[OfficeAutomation_Document_Feasibility_RateBeginDate]"
                           + "           ,[OfficeAutomation_Document_Feasibility_RateEndDate]"
                           + "           ,[OfficeAutomation_Document_Feasibility_Address]"
                           + "           ,[OfficeAutomation_Document_Feasibility_Square]"
                           + "           ,[OfficeAutomation_Document_Feasibility_RentSituation]"
                           + "           ,[OfficeAutomation_Document_Feasibility_Deposit]"
                           + "           ,[OfficeAutomation_Document_Feasibility_SendCoast]"
                           + "           ,[OfficeAutomation_Document_Feasibility_PropertySituation]"
                           + "           ,[OfficeAutomation_Document_Feasibility_RentAndTurn]"
                           + "           ,[OfficeAutomation_Document_Feasibility_PowerAddS]"
                           + "           ,[OfficeAutomation_Document_Feasibility_MTelephone]"
                           + "           ,[OfficeAutomation_Document_Feasibility_MOptical]"
                           + "           ,[OfficeAutomation_Document_Feasibility_MonthlyPerformance]"
                           + "           ,[OfficeAutomation_Document_Feasibility_ReachDate]"
                           + "           ,[OfficeAutomation_Document_Feasibility_TotalCost]"
                           + "           ,[OfficeAutomation_Document_Feasibility_NormalCost]"
                           + "           ,[OfficeAutomation_Document_Feasibility_MonthProfit]"
                           + "           ,[OfficeAutomation_Document_Feasibility_MonthProfitRDate]"
                           + "           ,[OfficeAutomation_Document_Feasibility_ReturnPeriod]"
                           + "           ,[OfficeAutomation_Document_Feasibility_BankOnForecast]"
                           + "           ,[OfficeAutomation_Document_Feasibility_BuildArea]"
                           + "           ,[OfficeAutomation_Document_Feasibility_UsableArea]"
                           + "           ,[OfficeAutomation_Document_Feasibility_LeaseStartDate]"
                           + "           ,[OfficeAutomation_Document_Feasibility_LeaseEndDate]"
                           + "           ,[OfficeAutomation_Document_Feasibility_LeaseYears]"
                           + "           ,[OfficeAutomation_Document_Feasibility_LeaseMonths]"
                           + "           ,[OfficeAutomation_Document_Feasibility_IsRentFree]"
                           + "           ,[OfficeAutomation_Document_Feasibility_RentFreeStart]"
                           + "           ,[OfficeAutomation_Document_Feasibility_txtRentFreeEnd]"
                           + "           ,[OfficeAutomation_Document_Feasibility_RentFreeCount]"
                           + "           ,[OfficeAutomation_Document_Feasibility_MonthlyRentNoTax]"
                           + "           ,[OfficeAutomation_Document_Feasibility_MonthlyRentIncludeTax]"
                           + "           ,[OfficeAutomation_Document_Feasibility_MothlyTax]"
                           + "           ,[OfficeAutomation_Document_Feasibility_HasTax]"
                           + "           ,[OfficeAutomation_Document_Feasibility_MonthlyTaxRate]"
                           + "           ,[OfficeAutomation_Document_Feasibility_ManageCoast]"
                           + "           ,[OfficeAutomation_Document_Feasibility_ManageCoast2]"
                           + "           ,[OfficeAutomation_Document_Feasibility_WCoast]"
                           + "           ,[OfficeAutomation_Document_Feasibility_ECoast]"
                           + "           ,[OfficeAutomation_Document_Feasibility_Invoice]"
                           + "           ,[OfficeAutomation_Document_Feasibility_RentDeposit]"
                           + "           ,[OfficeAutomation_Document_Feasibility_WEDeposit]"
                           + "           ,[OfficeAutomation_Document_Feasibility_ManageDeposit]"
                           + "           ,[OfficeAutomation_Document_Feasibility_PackageInvoice]"
                           + "           ,[OfficeAutomation_Document_Feasibility_NPackageInvoice]"
                           + "           ,[OfficeAutomation_Document_Feasibility_PayReason]"
                           + "           ,[OfficeAutomation_Document_Feasibility_PayWay]"
                           + "           ,[OfficeAutomation_Document_Feasibility_PayObiect]"
                           + "           ,[OfficeAutomation_Document_Feasibility_POPhone]"
                           + "           ,[OfficeAutomation_Document_Feasibility_Collection]"
                           + "           ,[OfficeAutomation_Document_Feasibility_CollectionPhone]"
                           + "           ,[OfficeAutomation_Document_Feasibility_Relationship]"
                           + "           ,[OfficeAutomation_Document_Feasibility_StampDuty]"
                           + "           ,[OfficeAutomation_Document_Feasibility_StampDuty0]"
                           + "           ,[OfficeAutomation_Document_Feasibility_CompleteDate]"
                           + "           ,[OfficeAutomation_Document_Feasibility_FirstRent]"
                           + "           ,[OfficeAutomation_Document_Feasibility_LeaseDeposit]"
                           + "           ,[OfficeAutomation_Document_Feasibility_FSendCoast]"
                           + "           ,[OfficeAutomation_Document_Feasibility_FWEDeposit]"
                           + "           ,[OfficeAutomation_Document_Feasibility_FManageDeposit]"
                           + "           ,[OfficeAutomation_Document_Feasibility_FFMCoaet]"
                           + "           ,[OfficeAutomation_Document_Feasibility_FirstRentC]"
                           + "           ,[OfficeAutomation_Document_Feasibility_LeaseDepositC]"
                           + "           ,[OfficeAutomation_Document_Feasibility_FSendCoastC]"
                           + "           ,[OfficeAutomation_Document_Feasibility_FWEDepositC]"
                           + "           ,[OfficeAutomation_Document_Feasibility_FManageDepositC]"
                           + "           ,[OfficeAutomation_Document_Feasibility_FFMCoaetC]"
                           + "           ,[OfficeAutomation_Document_Feasibility_FirstRentT]"
                           + "           ,[OfficeAutomation_Document_Feasibility_LeaseDepositT]"
                           + "           ,[OfficeAutomation_Document_Feasibility_FSendCoastT]"
                           + "           ,[OfficeAutomation_Document_Feasibility_FWEDepositT]"
                           + "           ,[OfficeAutomation_Document_Feasibility_FManageDepositT]"
                           + "           ,[OfficeAutomation_Document_Feasibility_FFMCoaetT]"
                           + "           ,[OfficeAutomation_Document_Feasibility_RentName]"
                           + "           ,[OfficeAutomation_Document_Feasibility_RentReal]"
                           + "           ,[OfficeAutomation_Document_Feasibility_RentIdentity]"
                           + "           ,[OfficeAutomation_Document_Feasibility_RentMessage]"
                           + "           ,[OfficeAutomation_Document_Feasibility_EstateProperties]"
                           + "           ,[OfficeAutomation_Document_Feasibility_NatureTitle]"
                           + "           ,[OfficeAutomation_Document_Feasibility_NatureTitleO]"
                           + "           ,[OfficeAutomation_Document_Feasibility_Summary]"
                           + "           ,toam.OfficeAutomation_SerialNumber"
                           + "           ,tdoad.OfficeAutomation_Document_Name"
                           + "           ,toam.OfficeAutomation_Main_FlowStateID"
                           + " FROM [DB_EcOfficeAutomation].[dbo].[t_OfficeAutomation_Document_Feasibility] todi"
                           + " LEFT JOIN t_OfficeAutomation_Main toam ON toam.OfficeAutomation_Main_ID= todi.OfficeAutomation_Document_Feasibility_MainID"
                           + " LEFT JOIN t_Dic_OfficeAutomation_Document tdoad ON tdoad.OfficeAutomation_Document_ID = toam.OfficeAutomation_DocumentID"
                           + " WHERE OfficeAutomation_Document_Feasibility_ID='" + ID + "'";

            return RunSQL(sql);
        }
        public byte[] ReadPhoto(string mainID)
        {
            string sql = "SELECT  [OfficeAutomation_Document_Feasibility_Diagram_Photo]"
                           + " FROM [DB_EcOfficeAutomation].[dbo].[t_OfficeAutomation_Document_Feasibility_Diagram]"
                           + " WHERE OfficeAutomation_Document_Feasibility_Diagram_MainID='" + mainID + "'";
            return GetPhotos(sql);
        }

        #region 自定义
        //插入或者修改关键内容
        public bool HandleBase(T_OfficeAutomation_Document_Feasibility obj)
        {
            if (obj == null || obj.OfficeAutomation_Document_Feasibility_MainID == null)
            { return false; }

            var Baseobj = new DataEntity.T_OfficeAutomation_Document_Feasibility();
            Baseobj.OfficeAutomation_Document_Feasibility_ID = obj.OfficeAutomation_Document_Feasibility_ID;
            Baseobj.OfficeAutomation_Document_Feasibility_MainID = obj.OfficeAutomation_Document_Feasibility_MainID;
            Baseobj.OfficeAutomation_Document_Feasibility_Apply = obj.OfficeAutomation_Document_Feasibility_Apply;
            Baseobj.OfficeAutomation_Document_Feasibility_ApplyDate = Convert.ToDateTime(obj.OfficeAutomation_Document_Feasibility_ApplyDate);
            Baseobj.OfficeAutomation_Document_Feasibility_ApplyID = obj.OfficeAutomation_Document_Feasibility_ApplyID;
            Baseobj.OfficeAutomation_Document_Feasibility_Department = obj.OfficeAutomation_Document_Feasibility_Department;


            //obj是否已经存在
            var where = "[OfficeAutomation_Document_Feasibility_MainID]='" + obj.OfficeAutomation_Document_Feasibility_MainID.ToString() + "'";
            DataEntity.T_OfficeAutomation_Document_Feasibility resultobj;
            if (Exist(where))
            {
                //Edit
                resultobj = Edit(Baseobj);
            }
            else
            {
                //Add
                resultobj = Add(Baseobj);
            }
            return resultobj != null;
        }

        #endregion
    }
}
