//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.34209 版自动生成。
// 
#pragma warning disable 1591

namespace DataAccess.WS_CCES {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ContractService_GZSoap", Namespace="http://tempuri.org/")]
    public partial class ContractService_GZ : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetEstateListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPropertyListOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveContract_GZOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveContractAdjust_GZOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveContractFileOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ContractService_GZ() {
            this.Url = global::DataAccess.Properties.Settings.Default.DataAccess_WS_CCES_ContractService_GZ;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetEstateListCompletedEventHandler GetEstateListCompleted;
        
        /// <remarks/>
        public event GetPropertyListCompletedEventHandler GetPropertyListCompleted;
        
        /// <remarks/>
        public event SaveContract_GZCompletedEventHandler SaveContract_GZCompleted;
        
        /// <remarks/>
        public event SaveContractAdjust_GZCompletedEventHandler SaveContractAdjust_GZCompleted;
        
        /// <remarks/>
        public event SaveContractFileCompletedEventHandler SaveContractFileCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetEstateList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetEstateList(string strJson, string strFormat) {
            object[] results = this.Invoke("GetEstateList", new object[] {
                        strJson,
                        strFormat});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetEstateListAsync(string strJson, string strFormat) {
            this.GetEstateListAsync(strJson, strFormat, null);
        }
        
        /// <remarks/>
        public void GetEstateListAsync(string strJson, string strFormat, object userState) {
            if ((this.GetEstateListOperationCompleted == null)) {
                this.GetEstateListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEstateListOperationCompleted);
            }
            this.InvokeAsync("GetEstateList", new object[] {
                        strJson,
                        strFormat}, this.GetEstateListOperationCompleted, userState);
        }
        
        private void OnGetEstateListOperationCompleted(object arg) {
            if ((this.GetEstateListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEstateListCompleted(this, new GetEstateListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPropertyList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetPropertyList(string strJson, string strFormat) {
            object[] results = this.Invoke("GetPropertyList", new object[] {
                        strJson,
                        strFormat});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetPropertyListAsync(string strJson, string strFormat) {
            this.GetPropertyListAsync(strJson, strFormat, null);
        }
        
        /// <remarks/>
        public void GetPropertyListAsync(string strJson, string strFormat, object userState) {
            if ((this.GetPropertyListOperationCompleted == null)) {
                this.GetPropertyListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPropertyListOperationCompleted);
            }
            this.InvokeAsync("GetPropertyList", new object[] {
                        strJson,
                        strFormat}, this.GetPropertyListOperationCompleted, userState);
        }
        
        private void OnGetPropertyListOperationCompleted(object arg) {
            if ((this.GetPropertyListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPropertyListCompleted(this, new GetPropertyListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SaveContract_GZ", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode SaveContract_GZ(string strJson, string strFormat) {
            object[] results = this.Invoke("SaveContract_GZ", new object[] {
                        strJson,
                        strFormat});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void SaveContract_GZAsync(string strJson, string strFormat) {
            this.SaveContract_GZAsync(strJson, strFormat, null);
        }
        
        /// <remarks/>
        public void SaveContract_GZAsync(string strJson, string strFormat, object userState) {
            if ((this.SaveContract_GZOperationCompleted == null)) {
                this.SaveContract_GZOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveContract_GZOperationCompleted);
            }
            this.InvokeAsync("SaveContract_GZ", new object[] {
                        strJson,
                        strFormat}, this.SaveContract_GZOperationCompleted, userState);
        }
        
        private void OnSaveContract_GZOperationCompleted(object arg) {
            if ((this.SaveContract_GZCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveContract_GZCompleted(this, new SaveContract_GZCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SaveContractAdjust_GZ", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode SaveContractAdjust_GZ(string strJson, string strFormat) {
            object[] results = this.Invoke("SaveContractAdjust_GZ", new object[] {
                        strJson,
                        strFormat});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void SaveContractAdjust_GZAsync(string strJson, string strFormat) {
            this.SaveContractAdjust_GZAsync(strJson, strFormat, null);
        }
        
        /// <remarks/>
        public void SaveContractAdjust_GZAsync(string strJson, string strFormat, object userState) {
            if ((this.SaveContractAdjust_GZOperationCompleted == null)) {
                this.SaveContractAdjust_GZOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveContractAdjust_GZOperationCompleted);
            }
            this.InvokeAsync("SaveContractAdjust_GZ", new object[] {
                        strJson,
                        strFormat}, this.SaveContractAdjust_GZOperationCompleted, userState);
        }
        
        private void OnSaveContractAdjust_GZOperationCompleted(object arg) {
            if ((this.SaveContractAdjust_GZCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveContractAdjust_GZCompleted(this, new SaveContractAdjust_GZCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SaveContractFile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode SaveContractFile(string strJson, string strFormat) {
            object[] results = this.Invoke("SaveContractFile", new object[] {
                        strJson,
                        strFormat});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void SaveContractFileAsync(string strJson, string strFormat) {
            this.SaveContractFileAsync(strJson, strFormat, null);
        }
        
        /// <remarks/>
        public void SaveContractFileAsync(string strJson, string strFormat, object userState) {
            if ((this.SaveContractFileOperationCompleted == null)) {
                this.SaveContractFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveContractFileOperationCompleted);
            }
            this.InvokeAsync("SaveContractFile", new object[] {
                        strJson,
                        strFormat}, this.SaveContractFileOperationCompleted, userState);
        }
        
        private void OnSaveContractFileOperationCompleted(object arg) {
            if ((this.SaveContractFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveContractFileCompleted(this, new SaveContractFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetEstateListCompletedEventHandler(object sender, GetEstateListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEstateListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEstateListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetPropertyListCompletedEventHandler(object sender, GetPropertyListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPropertyListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPropertyListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void SaveContract_GZCompletedEventHandler(object sender, SaveContract_GZCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveContract_GZCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveContract_GZCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void SaveContractAdjust_GZCompletedEventHandler(object sender, SaveContractAdjust_GZCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveContractAdjust_GZCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveContractAdjust_GZCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void SaveContractFileCompletedEventHandler(object sender, SaveContractFileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveContractFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveContractFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591